maxConcurrent = 5

# Processes
[[process]]
name = "CronProcess"
cron = "*"
cwd = "/path/to/process"
command = "php"
args = ["process.php"]

[[process]]
name = "HTTP Server"
cwd = "/path/to/process"
command = "node"
args = ["server.js"]
keepAlive = true

[[process]]
name = "HTTP Server"
cwd = "/path/to/process"
command = "node"
args = ["server.js"]
keepAlive = true



